#ifndef GENERATED_DATA_H
#define GENERATED_DATA_H

/* 
 * AUTO-GENERATED FILE - DO NOT MODIFY 
 * Generated by scripts/generate_data.py
 */

#include "combat.h"
#include <string.h>

// --- Monsters ---
#define MONSTER_DB_SIZE 13

static const Monster g_monster_db[MONSTER_DB_SIZE] = {
    { .id = 1, .name = "파란 달팽이", .max_hp = 300, .hp = 300, .def = 5, .is_boss = 0, .loot = { .name = "달팽이 껍질", .value = 10 } },
    { .id = 2, .name = "슬라임", .max_hp = 600, .hp = 600, .def = 10, .is_boss = 0, .loot = { .name = "슬라임의 핵", .value = 20 } },
    { .id = 3, .name = "주황버섯", .max_hp = 1500, .hp = 1500, .def = 30, .is_boss = 0, .loot = { .name = "버섯 갓", .value = 50 } },
    { .id = 4, .name = "🍄 머쉬맘 (BOSS) 🍄", .max_hp = 10000, .hp = 10000, .def = 100, .is_boss = 1, .loot = { .name = "머쉬맘의 포자", .value = 500 } },
    { .id = 5, .name = "오크", .max_hp = 8000, .hp = 8000, .def = 80, .is_boss = 0, .loot = { .name = "오크의 이빨", .value = 150 } },
    { .id = 6, .name = "와일드카고", .max_hp = 15000, .hp = 15000, .def = 150, .is_boss = 0, .loot = { .name = "와일드카고의 눈동자", .value = 250 } },
    { .id = 7, .name = "🔥 자쿰의 팔 (BOSS) 🔥", .max_hp = 50000, .hp = 50000, .def = 300, .is_boss = 1, .loot = { .name = "자쿰의 나뭇가지", .value = 2000 } },
    { .id = 8, .name = "스켈레톤", .max_hp = 50000, .hp = 50000, .def = 300, .is_boss = 0, .loot = { .name = "부서진 뼈", .value = 600 } },
    { .id = 9, .name = "다크 레인저", .max_hp = 80000, .hp = 80000, .def = 400, .is_boss = 0, .loot = { .name = "검은 화살촉", .value = 1000 } },
    { .id = 10, .name = "🕒 파풀라투스 (BOSS) 🕒", .max_hp = 300000, .hp = 300000, .def = 600, .is_boss = 1, .loot = { .name = "시계 파편", .value = 8000 } },
    { .id = 11, .name = "블루 와이번", .max_hp = 200000, .hp = 200000, .def = 600, .is_boss = 0, .loot = { .name = "와이번의 발톱", .value = 2500 } },
    { .id = 12, .name = "다크 코르니안", .max_hp = 400000, .hp = 400000, .def = 800, .is_boss = 0, .loot = { .name = "단단한 비늘", .value = 4000 } },
    { .id = 13, .name = "🌸 핑크빈 (BOSS) 🌸", .max_hp = 1200000, .hp = 1200000, .def = 1200, .is_boss = 1, .loot = { .name = "핑크빈의 인형", .value = 30000 } }
};

// Helper to find monster by ID
static inline Monster get_monster_by_id(int id) {
    for (int i = 0; i < MONSTER_DB_SIZE; i++) {
        if (g_monster_db[i].id == id) return g_monster_db[i];
    }
    Monster null_monster = {0};
    return null_monster;
}

// --- Dungeons ---
#define DUNGEON_COUNT 5

// Data structure for initial dungeon setup
typedef struct {
    char name[50];
    int min_cp;
    int max_cp;
    int monster_ids[3];
    int monster_count;
    int has_boss;
    int boss_id;
} DungeonTemplate;

static const DungeonTemplate g_dungeon_templates[DUNGEON_COUNT] = {
    { .name = "초심자의 들판", .min_cp = 0, .max_cp = 500, .monster_ids = { 1, 2, 0 }, .monster_count = 3, .has_boss = 0, .boss_id = 0 },
    { .name = "노란 버섯 동산", .min_cp = 500, .max_cp = 2000, .monster_ids = { 3, 0, 0 }, .monster_count = 3, .has_boss = 1, .boss_id = 4 },
    { .name = "축축한 습지", .min_cp = 2000, .max_cp = 5000, .monster_ids = { 5, 6, 0 }, .monster_count = 3, .has_boss = 1, .boss_id = 7 },
    { .name = "잊혀진 신전", .min_cp = 5000, .max_cp = 15000, .monster_ids = { 8, 9, 0 }, .monster_count = 3, .has_boss = 1, .boss_id = 10 },
    { .name = "검은 용의 둥지", .min_cp = 15000, .max_cp = 999999, .monster_ids = { 11, 12, 0 }, .monster_count = 3, .has_boss = 1, .boss_id = 13 }
};

#endif
