import json
import os

def generate_header():
    # Load monsters
    with open('data/monsters.json', 'r', encoding='utf-8') as f:
        monsters = json.load(f)
    
    # Load dungeons
    with open('data/dungeons.json', 'r', encoding='utf-8') as f:
        dungeons = json.load(f)

    header_content = """#ifndef GENERATED_DATA_H
#define GENERATED_DATA_H

/* 
 * AUTO-GENERATED FILE - DO NOT MODIFY 
 * Generated by scripts/generate_data.py
 */

#include "combat.h"
#include <string.h>

// --- Monsters ---
#define MONSTER_DB_SIZE {m_size}

static const Monster g_monster_db[MONSTER_DB_SIZE] = {{
{m_entries}
}};

// Helper to find monster by ID
static inline Monster get_monster_by_id(int id) {{
    for (int i = 0; i < MONSTER_DB_SIZE; i++) {{
        if (g_monster_db[i].id == id) return g_monster_db[i];
    }}
    Monster null_monster = {{0}};
    return null_monster;
}}

// --- Dungeons ---
#define DUNGEON_COUNT {d_size}

// Data structure for initial dungeon setup
typedef struct {{
    char name[50];
    int min_cp;
    int max_cp;
    int monster_ids[3];
    int monster_count;
    int has_boss;
    int boss_id;
}} DungeonTemplate;

static const DungeonTemplate g_dungeon_templates[DUNGEON_COUNT] = {{
{d_entries}
}};

#endif
"""

    m_entries = []
    for m in monsters:
        loot_name = m['loot']['name']
        loot_val = m['loot']['value']
        entry = f"    {{ .id = {m['id']}, .name = \"{m['name']}\", .max_hp = {m['hp']}, .hp = {m['hp']}, .def = {m['def']}, .is_boss = {m['is_boss']}, .loot = {{ .name = \"{loot_name}\", .value = {loot_val} }} }}"
        m_entries.append(entry)
    
    d_entries = []
    for d in dungeons:
        m_ids = d['monster_ids']
        while len(m_ids) < 3:
            m_ids.append(0)
        m_ids_str = ", ".join(map(str, m_ids))
        boss_id = d.get('boss_id', 0)
        entry = f"    {{ .name = \"{d['name']}\", .min_cp = {d['min_cp']}, .max_cp = {d['max_cp']}, .monster_ids = {{ {m_ids_str} }}, .monster_count = {len(d['monster_ids'])}, .has_boss = {d['has_boss']}, .boss_id = {boss_id} }}"
        d_entries.append(entry)

    final_header = header_content.format(
        m_size=len(monsters),
        m_entries=",\n".join(m_entries),
        d_size=len(dungeons),
        d_entries=",\n".join(d_entries)
    )

    os.makedirs('include', exist_ok=True)
    with open('include/generated_data.h', 'w', encoding='utf-8') as f:
        f.write(final_header)
    
    print("Successfully generated include/generated_data.h")

if __name__ == "__main__":
    generate_header()
